package postgres

import (
	"context"

	"github.com/jmoiron/sqlx"
	"github.com/raymondwongso/goerp/domain"
	"go.opentelemetry.io/otel/trace"
)

type sessionWriter struct {
	tracer trace.Tracer
	db     sqlx.QueryerContext
}

// NewSessionWriter creates a new sessionWriter
func NewSessionWriter(tracer trace.Tracer, db sqlx.QueryerContext) *sessionWriter {
	return &sessionWriter{
		tracer: tracer,
		db:     db,
	}
}

// Insert creates a new session. The session ID is generated by the database.
func (w *sessionWriter) Insert(ctx context.Context, session domain.Session) (domain.Session, error) {
	ctx, span := w.tracer.Start(ctx, "SessionWriter/Insert")
	defer span.End()

	query := `
		INSERT INTO sessions (user_id, ip_address, user_agent)
		VALUES ($1, $2, $3)
		RETURNING id, user_id, ip_address, user_agent, is_revoked, absolute_expiry, created_at, last_seen_at`

	row := w.db.QueryRowxContext(ctx, query, session.UserID, session.IPAddress, session.UserAgent)
	if err := row.Err(); err != nil {
		return domain.Session{}, err
	}

	var res domain.Session
	if err := row.StructScan(&res); err != nil {
		return domain.Session{}, err
	}
	return res, nil
}
