// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -package=mockauth -source=interfaces.go -destination=mock/mock_interfaces.go
//

// Package mockauth is a generated GoMock package.
package mockauth

import (
	context "context"
	reflect "reflect"

	auth "github.com/raymondwongso/goerp/domain/auth"
	gomock "go.uber.org/mock/gomock"
)

// MockGoogleLogin is a mock of GoogleLogin interface.
type MockGoogleLogin struct {
	ctrl     *gomock.Controller
	recorder *MockGoogleLoginMockRecorder
	isgomock struct{}
}

// MockGoogleLoginMockRecorder is the mock recorder for MockGoogleLogin.
type MockGoogleLoginMockRecorder struct {
	mock *MockGoogleLogin
}

// NewMockGoogleLogin creates a new mock instance.
func NewMockGoogleLogin(ctrl *gomock.Controller) *MockGoogleLogin {
	mock := &MockGoogleLogin{ctrl: ctrl}
	mock.recorder = &MockGoogleLoginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGoogleLogin) EXPECT() *MockGoogleLoginMockRecorder {
	return m.recorder
}

// Invoke mocks base method.
func (m *MockGoogleLogin) Invoke(ctx context.Context, req auth.GoogleLoginRequest) (auth.GoogleLoginResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Invoke", ctx, req)
	ret0, _ := ret[0].(auth.GoogleLoginResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Invoke indicates an expected call of Invoke.
func (mr *MockGoogleLoginMockRecorder) Invoke(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Invoke", reflect.TypeOf((*MockGoogleLogin)(nil).Invoke), ctx, req)
}

// MockGoogleCallback is a mock of GoogleCallback interface.
type MockGoogleCallback struct {
	ctrl     *gomock.Controller
	recorder *MockGoogleCallbackMockRecorder
	isgomock struct{}
}

// MockGoogleCallbackMockRecorder is the mock recorder for MockGoogleCallback.
type MockGoogleCallbackMockRecorder struct {
	mock *MockGoogleCallback
}

// NewMockGoogleCallback creates a new mock instance.
func NewMockGoogleCallback(ctrl *gomock.Controller) *MockGoogleCallback {
	mock := &MockGoogleCallback{ctrl: ctrl}
	mock.recorder = &MockGoogleCallbackMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGoogleCallback) EXPECT() *MockGoogleCallbackMockRecorder {
	return m.recorder
}

// Invoke mocks base method.
func (m *MockGoogleCallback) Invoke(ctx context.Context, req auth.GoogleCallbackRequest) (auth.GoogleCallbackResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Invoke", ctx, req)
	ret0, _ := ret[0].(auth.GoogleCallbackResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Invoke indicates an expected call of Invoke.
func (mr *MockGoogleCallbackMockRecorder) Invoke(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Invoke", reflect.TypeOf((*MockGoogleCallback)(nil).Invoke), ctx, req)
}
