// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -package=mockexample -source=interfaces.go -destination=mock/mock_interfaces.go
//

// Package mockexample is a generated GoMock package.
package mockexample

import (
	context "context"
	reflect "reflect"

	domain "github.com/raymondwongso/goerp/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockSubmoduleACreate is a mock of SubmoduleACreate interface.
type MockSubmoduleACreate struct {
	ctrl     *gomock.Controller
	recorder *MockSubmoduleACreateMockRecorder
	isgomock struct{}
}

// MockSubmoduleACreateMockRecorder is the mock recorder for MockSubmoduleACreate.
type MockSubmoduleACreateMockRecorder struct {
	mock *MockSubmoduleACreate
}

// NewMockSubmoduleACreate creates a new mock instance.
func NewMockSubmoduleACreate(ctrl *gomock.Controller) *MockSubmoduleACreate {
	mock := &MockSubmoduleACreate{ctrl: ctrl}
	mock.recorder = &MockSubmoduleACreateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubmoduleACreate) EXPECT() *MockSubmoduleACreateMockRecorder {
	return m.recorder
}

// Invoke mocks base method.
func (m *MockSubmoduleACreate) Invoke(ctx context.Context, example domain.Example) (domain.Example, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Invoke", ctx, example)
	ret0, _ := ret[0].(domain.Example)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Invoke indicates an expected call of Invoke.
func (mr *MockSubmoduleACreateMockRecorder) Invoke(ctx, example any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Invoke", reflect.TypeOf((*MockSubmoduleACreate)(nil).Invoke), ctx, example)
}

// MockSubmoduleBGet is a mock of SubmoduleBGet interface.
type MockSubmoduleBGet struct {
	ctrl     *gomock.Controller
	recorder *MockSubmoduleBGetMockRecorder
	isgomock struct{}
}

// MockSubmoduleBGetMockRecorder is the mock recorder for MockSubmoduleBGet.
type MockSubmoduleBGetMockRecorder struct {
	mock *MockSubmoduleBGet
}

// NewMockSubmoduleBGet creates a new mock instance.
func NewMockSubmoduleBGet(ctrl *gomock.Controller) *MockSubmoduleBGet {
	mock := &MockSubmoduleBGet{ctrl: ctrl}
	mock.recorder = &MockSubmoduleBGetMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubmoduleBGet) EXPECT() *MockSubmoduleBGetMockRecorder {
	return m.recorder
}

// Invoke mocks base method.
func (m *MockSubmoduleBGet) Invoke(ctx context.Context, id int64) (domain.Example, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Invoke", ctx, id)
	ret0, _ := ret[0].(domain.Example)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Invoke indicates an expected call of Invoke.
func (mr *MockSubmoduleBGetMockRecorder) Invoke(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Invoke", reflect.TypeOf((*MockSubmoduleBGet)(nil).Invoke), ctx, id)
}
