// Code generated by MockGen. DO NOT EDIT.
// Source: session.go
//
// Generated by this command:
//
//	mockgen -package=mockdomain -source=session.go -destination=mock/mock_session.go
//

// Package mockdomain is a generated GoMock package.
package mockdomain

import (
	context "context"
	reflect "reflect"

	domain "github.com/raymondwongso/goerp/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockSessionWriter is a mock of SessionWriter interface.
type MockSessionWriter struct {
	ctrl     *gomock.Controller
	recorder *MockSessionWriterMockRecorder
	isgomock struct{}
}

// MockSessionWriterMockRecorder is the mock recorder for MockSessionWriter.
type MockSessionWriterMockRecorder struct {
	mock *MockSessionWriter
}

// NewMockSessionWriter creates a new mock instance.
func NewMockSessionWriter(ctrl *gomock.Controller) *MockSessionWriter {
	mock := &MockSessionWriter{ctrl: ctrl}
	mock.recorder = &MockSessionWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionWriter) EXPECT() *MockSessionWriterMockRecorder {
	return m.recorder
}

// Insert mocks base method.
func (m *MockSessionWriter) Insert(ctx context.Context, session domain.Session) (domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, session)
	ret0, _ := ret[0].(domain.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockSessionWriterMockRecorder) Insert(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockSessionWriter)(nil).Insert), ctx, session)
}
