// Code generated by MockGen. DO NOT EDIT.
// Source: oauth.go
//
// Generated by this command:
//
//	mockgen -package=mockdomain -source=oauth.go -destination=mock/mock_oauth.go
//

// Package mockdomain is a generated GoMock package.
package mockdomain

import (
	context "context"
	reflect "reflect"

	domain "github.com/raymondwongso/goerp/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockOAuthStateWriter is a mock of OAuthStateWriter interface.
type MockOAuthStateWriter struct {
	ctrl     *gomock.Controller
	recorder *MockOAuthStateWriterMockRecorder
	isgomock struct{}
}

// MockOAuthStateWriterMockRecorder is the mock recorder for MockOAuthStateWriter.
type MockOAuthStateWriterMockRecorder struct {
	mock *MockOAuthStateWriter
}

// NewMockOAuthStateWriter creates a new mock instance.
func NewMockOAuthStateWriter(ctrl *gomock.Controller) *MockOAuthStateWriter {
	mock := &MockOAuthStateWriter{ctrl: ctrl}
	mock.recorder = &MockOAuthStateWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOAuthStateWriter) EXPECT() *MockOAuthStateWriterMockRecorder {
	return m.recorder
}

// DeleteByState mocks base method.
func (m *MockOAuthStateWriter) DeleteByState(ctx context.Context, state string) (domain.OAuthState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByState", ctx, state)
	ret0, _ := ret[0].(domain.OAuthState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteByState indicates an expected call of DeleteByState.
func (mr *MockOAuthStateWriterMockRecorder) DeleteByState(ctx, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByState", reflect.TypeOf((*MockOAuthStateWriter)(nil).DeleteByState), ctx, state)
}

// Insert mocks base method.
func (m *MockOAuthStateWriter) Insert(ctx context.Context, state domain.OAuthState) (domain.OAuthState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, state)
	ret0, _ := ret[0].(domain.OAuthState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockOAuthStateWriterMockRecorder) Insert(ctx, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockOAuthStateWriter)(nil).Insert), ctx, state)
}

// MockOAuthAccountWriter is a mock of OAuthAccountWriter interface.
type MockOAuthAccountWriter struct {
	ctrl     *gomock.Controller
	recorder *MockOAuthAccountWriterMockRecorder
	isgomock struct{}
}

// MockOAuthAccountWriterMockRecorder is the mock recorder for MockOAuthAccountWriter.
type MockOAuthAccountWriterMockRecorder struct {
	mock *MockOAuthAccountWriter
}

// NewMockOAuthAccountWriter creates a new mock instance.
func NewMockOAuthAccountWriter(ctrl *gomock.Controller) *MockOAuthAccountWriter {
	mock := &MockOAuthAccountWriter{ctrl: ctrl}
	mock.recorder = &MockOAuthAccountWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOAuthAccountWriter) EXPECT() *MockOAuthAccountWriterMockRecorder {
	return m.recorder
}

// Upsert mocks base method.
func (m *MockOAuthAccountWriter) Upsert(ctx context.Context, account domain.OAuthAccount) (domain.OAuthAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, account)
	ret0, _ := ret[0].(domain.OAuthAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upsert indicates an expected call of Upsert.
func (mr *MockOAuthAccountWriterMockRecorder) Upsert(ctx, account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockOAuthAccountWriter)(nil).Upsert), ctx, account)
}
