// Code generated by MockGen. DO NOT EDIT.
// Source: google.go
//
// Generated by this command:
//
//	mockgen -package=mockgoogle -source=google.go -destination=mock/mock_google.go
//

// Package mockgoogle is a generated GoMock package.
package mockgoogle

import (
	context "context"
	reflect "reflect"

	google "github.com/raymondwongso/goerp/domain/google"
	gomock "go.uber.org/mock/gomock"
)

// MockTokenProvider is a mock of TokenProvider interface.
type MockTokenProvider struct {
	ctrl     *gomock.Controller
	recorder *MockTokenProviderMockRecorder
	isgomock struct{}
}

// MockTokenProviderMockRecorder is the mock recorder for MockTokenProvider.
type MockTokenProviderMockRecorder struct {
	mock *MockTokenProvider
}

// NewMockTokenProvider creates a new mock instance.
func NewMockTokenProvider(ctrl *gomock.Controller) *MockTokenProvider {
	mock := &MockTokenProvider{ctrl: ctrl}
	mock.recorder = &MockTokenProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenProvider) EXPECT() *MockTokenProviderMockRecorder {
	return m.recorder
}

// Exchange mocks base method.
func (m *MockTokenProvider) Exchange(ctx context.Context, code, codeVerifier string) (google.Claims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exchange", ctx, code, codeVerifier)
	ret0, _ := ret[0].(google.Claims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exchange indicates an expected call of Exchange.
func (mr *MockTokenProviderMockRecorder) Exchange(ctx, code, codeVerifier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exchange", reflect.TypeOf((*MockTokenProvider)(nil).Exchange), ctx, code, codeVerifier)
}

// GetAuthURL mocks base method.
func (m *MockTokenProvider) GetAuthURL(state, codeChallenge string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthURL", state, codeChallenge)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetAuthURL indicates an expected call of GetAuthURL.
func (mr *MockTokenProviderMockRecorder) GetAuthURL(state, codeChallenge any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthURL", reflect.TypeOf((*MockTokenProvider)(nil).GetAuthURL), state, codeChallenge)
}
